import { MissionStatus } from './entites/user-mission.entity';

export const ANDROID_BONUS_POINTS = 1000;
export const ANDROID_BONUS_MISSION_ID = 11;

export enum MissionAction {
  REFER = 'refer',
  FOLLOW = 'follow',
  TAG = 'tag',
  JOIN = 'join',
  CONNECT = 'connect',
  MERGE = 'merge',
  CREATE_ACCOUNT = 'create_account',
}

export const MISSIONS_LIST = [
  {
    id: 1,
    title: 'Refer a Friend',
    description:
      'Invite a friend and earn points when they create their Doppelganger.',
    action: MissionAction.REFER,
    status: MissionStatus.TODO,
    done: false,
    points: 1000,
    link: 'referral link',
  },
  {
    id: 2,
    title: 'Follow Us on X',
    description: 'Stay in the loop! Follow us on X and get the latest updates.',
    action: MissionAction.FOLLOW,
    status: MissionStatus.TODO,
    done: false,
    points: 300,
    link: 'https://x.com/Doppelgangerai',
    iosLink: 'x://profile?username=Doppelgangerai',
    androidLink: 'x://profile?username=Doppelgangerai',
  },
  {
    id: 3,
    title: 'Tag Us in a Post on X',
    description: 'Post or reshare with our tag on X and score some rewards!',
    action: MissionAction.TAG,
    status: MissionStatus.TODO,
    done: false,
    points: 500,
    link: 'https://x.com/compose/post',
    iosLink: 'x://post',
    androidLink: 'x://post',
  },
  {
    id: 4,
    title: 'Follow Us on Instagram',
    description: 'Follow us on Instagram and stay inspired with daily updates.',
    action: MissionAction.FOLLOW,
    status: MissionStatus.TODO,
    done: false,
    points: 300,
    link: 'https://www.instagram.com/doppelgangerscommunity',
    iosLink: 'instagram://user?username=doppelgangerscommunity',
    androidLink: 'instagram://user?username=doppelgangerscommunity',
  },
  {
    id: 5,
    title: 'Tag Us in an IG Post',
    description:
      'Share or reshare a post tagging us on Instagram to earn points.',
    action: MissionAction.TAG,
    status: MissionStatus.TODO,
    done: false,
    points: 500,
    link: 'https://instagram.com',
    iosLink: 'instagram://',
    androidLink: 'instagram://',
  },
  {
    id: 6,
    title: 'Join Our Discord',
    description: 'Be part of our community! Join Discord and chat with fans.',
    action: MissionAction.JOIN,
    status: MissionStatus.TODO,
    done: false,
    points: 600,
    link: 'https://discord.gg/8DAGgN3G',
    iosLink: 'discord://discord.gg/8DAGgN3G',
    androidLink: 'discord://discord.gg/8DAGgN3G',
  },
  {
    id: 7,
    title: 'Join Our Telegram',
    description: 'Join our Telegram for news and insights. Points await!',
    action: MissionAction.JOIN,
    status: MissionStatus.TODO,
    done: false,
    points: 600,
    link: 'https://t.me/doppelgangers_ai',
    iosLink: 'tg://resolve?domain=doppelgangers_ai',
    androidLink: 'tg://resolve?domain=doppelgangers_ai',
  },
  {
    id: 8,
    title: 'Connect Data Source in Vault',
    description:
      'Link a data source in your vault to enhance your twin\'s growth.',
    action: MissionAction.CONNECT,
    status: MissionStatus.TODO,
    done: false,
    points: 3000,
    link: 'link to vault',
  },
  {
    id: 9,
    title: 'Merge Your Doppelganger',
    description: 'Merge your Doppelganger to unlock its full potential.',
    action: MissionAction.MERGE,
    status: MissionStatus.TODO,
    done: false,
    points: 1000,
    link: 'merge button',
  },
  {
    id: 10,
    title: 'Create Your Doppelganger',
    description: 'Start your journey by creating your own digital twin.',
    action: MissionAction.CONNECT,
    status: MissionStatus.TODO,
    done: false,
    points: 5000,
    link: 'link to Vault',
  },
  {
    id: ANDROID_BONUS_MISSION_ID,
    title: 'Create Account on Android',
    description: 'Start your journey with us by creating an account on Android',
    action: MissionAction.CREATE_ACCOUNT,
    status: MissionStatus.DONE,
    points: ANDROID_BONUS_POINTS,
    done: false,
    link: null,
    androidOnly: true,
  },
];
