import { MissionStatus } from './entites/user-mission.entity';

export const MISSIONS_LIST = [
  {
    id: 1,
    title: 'Refer a Friend',
    description:
      'Invite a friend and earn points when they create their Doppelganger.',
    action: 'refer',
    status: MissionStatus.TODO,
    done: false,
    points: 1000,
    link: 'referral link',
  },
  {
    id: 2,
    title: 'Follow Us on X',
    description: 'Stay in the loop! Follow us on X and get the latest updates.',
    action: 'follow',
    status: MissionStatus.TODO,
    done: false,
    points: 300,
    link: 'https://x.com/Doppelgangerai',
  },
  {
    id: 3,
    title: 'Tag Us in a Post on X',
    description: 'Post or reshare with our tag on X and score some rewards!',
    action: 'tag',
    status: MissionStatus.TODO,
    done: false,
    points: 500,
    link: 'https://x.com/compose/post',
  },
  {
    id: 4,
    title: 'Follow Us on Instagram',
    description: 'Follow us on Instagram and stay inspired with daily updates.',
    action: 'follow',
    status: MissionStatus.TODO,
    done: false,
    points: 300,
    link: 'https://www.instagram.com/doppelgangerscommunity',
  },
  {
    id: 5,
    title: 'Tag Us in an IG Post',
    description:
      'Share or reshare a post tagging us on Instagram to earn points.',
    action: 'tag',
    status: MissionStatus.TODO,
    done: false,
    points: 500,
    link: 'https://instagram.com',
  },
  {
    id: 6,
    title: 'Join Our Discord',
    description: 'Be part of our community! Join Discord and chat with fans.',
    action: 'join',
    status: MissionStatus.TODO,
    done: false,
    points: 600,
    link: 'https://discord.gg/8DAGgN3G',
  },
  {
    id: 7,
    title: 'Join Our Telegram',
    description: 'Join our Telegram for news and insights. Points await!',
    action: 'join',
    status: MissionStatus.TODO,
    done: false,
    points: 600,
    link: 'https://t.me/doppelgangers_ai',
  },
  {
    id: 8,
    title: 'Connect Data Source in Vault',
    description:
      'Link a data source in your vault to enhance your twin\'s growth.',
    action: 'connect',
    status: MissionStatus.TODO,
    done: false,
    points: 3000,
    link: 'link to vault',
  },
  {
    id: 9,
    title: 'Merge Your Doppelganger',
    description: 'Merge your Doppelganger to unlock its full potential.',
    action: 'merge',
    status: MissionStatus.TODO,
    done: false,
    points: 1000,
    link: 'merge button',
  },
  {
    id: 10,
    title: 'Create Your Doppelganger',
    description: 'Start your journey by creating your own digital twin.',
    action: 'connect',
    status: MissionStatus.TODO,
    done: false,
    points: 5000,
    link: 'link to Vault',
  },
];
